### PR TITLE
Fix typo in Slider Documentation

### PR DESCRIPTION
**Pull request by AbdullahAnsarii**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by 1uokun** [comment]
How do you Do it bro? Amazing🧐

**Comment by AbdullahAnsarii** [comment]
@1uokun Lol, Hire me as your documentation reviewer

**Comment by 1uokun** [comment]
`patch-2` branch was deleted bro, I need your code

**Comment by AbdullahAnsarii** [comment]
@1uokun I have reopened the pull request

**Comment by 1uokun** [comment]
Are you interested in an automatic typo detection? Like `textlint`

**Comment by AbdullahAnsarii** [comment]
Sure, it looks good

**Pull request merged**
