### PR TITLE
Upgrade dep

### PR DESCRIPTION
**Pull request by bang88**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [x] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by bang88** [comment]
@1uokun 我现在在升级依赖到最新版，并修复一些关联的bug。现在测试有问题，不知道你有没有空来一起看看。 或者换一个更好的测试方式 

谢谢

**Comment by 1uokun** [comment]
@bang88  说实话你想到了第五层，而我还在第一层🤦‍♂️
下班后要不要帮你把部分组件迁移到@react-native-community🤓

**Comment by bang88** [comment]
> @bang88 说实话你想到了第五层，而我还在第一层🤦‍♂️
😭 我先弄了一下，升级好多问题。

> 下班后要不要帮你把部分组件迁移到react-native-community🤓什么组件，暂时不想拆 之前拆了不好维护才合并的，现在主要就是修复bug，  react-native 更新一次要麻烦一次。

**Comment by 1uokun** [comment]
我刚拉你代码test跑下来报错的信息：
```console
Warning: XXX has been extracted from react-native core and will be removed in a future release. 
It can now be installed and imported from '@react-native-community/XXX' instead of 'react-native'. 
See https://github.com/react-native-community/XXX

```

**Comment by bang88** [comment]
> 我刚拉你代码test跑下来报错的信息：
> 
> ```
> Warning: XXX has been extracted from react-native core and will be removed in a future release. 
> It can now be installed and imported from '@react-native-community/XXX' instead of 'react-native'. 
> See https://github.com/react-native-community/XXX
> ```

upgrade-dep 分支，删掉 node_modules 重新安装，现在就是不知道是不是node的问题，还在查. 大部分能通过

**Comment by 1uokun** [comment]
> > 我刚拉你代码test跑下来报错的信息：
> > ```
> > Warning: XXX has been extracted from react-native core and will be removed in a future release. 
> > It can now be installed and imported from '@react-native-community/XXX' instead of 'react-native'. 
> > See https://github.com/react-native-community/XXX
> > ```
> 
> upgrade-dep 分支，删掉 node_modules 重新安装，现在就是不知道是不是node的问题，还在查. 大部分能通过

参考：https://github.com/facebook/react-native/commit/7e23c7c5654818fa076eeb627b709d39130f57f6

大概代码长这样：https://github.com/1uokun/ant-design-mobile-rn/commit/b04dbdd348c1636e204617ed97d6d5fa57c3482a

其他：
`0.59.4+`之后react-native取消了很多内置组件，比如swiper要引入的话要单独
```
- import { Swiper } from 'react-native'
+ import Swiper from '@react-native-community/picker'
```
还要link，不过这个版本之后变成自动link了

**Comment by bang88** [comment]
> > > 我刚拉你代码test跑下来报错的信息：
> > > ```
> > > Warning: XXX has been extracted from react-native core and will be removed in a future release. 
> > > It can now be installed and imported from '@react-native-community/XXX' instead of 'react-native'. 
> > > See https://github.com/react-native-community/XXX
> > > ```
> > 
> > 
> > upgrade-dep 分支，删掉 node_modules 重新安装，现在就是不知道是不是node的问题，还在查. 大部分能通过
> 
> 参考：[facebook/react-native@7e23c7c](https://github.com/facebook/react-native/commit/7e23c7c5654818fa076eeb627b709d39130f57f6)
> 
> 大概代码长这样：[1uokun@b04dbdd](https://github.com/1uokun/ant-design-mobile-rn/commit/b04dbdd348c1636e204617ed97d6d5fa57c3482a)
> 
> 其他：
> `0.59.4+`之后react-native取消了很多内置组件，比如swiper要引入的话要单独
> 
> ```
> - import { Swiper } from 'react-native'
> + import Swiper from '@react-native-community/picker'
> ```
> 
> 还要link，不过这个版本之后变成自动link了

明白你的意思了。 你是说把react-native里面分拆的组件，单独安装修改一下。  这个可以搞，我搞了两个，你看看还有什么要搞的。

安装依赖的时候记得 开发的时候装在dev依赖里面，但是peer里面的依赖也要有。

另外： tests 现在可以了，很奇葩的问题

**Pull request merged**
