### PR TITLE
feat：Toast 新增 remove、removeAll 回调

### PR DESCRIPTION
**Pull request by HuXin957**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [ ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ ] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [ ] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update TypeScript definition for the component.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by 1uokun** [comment]
针对 issue https://github.com/ant-design/ant-design-mobile-rn/issues/1195 提出的
```js
// 在调用Toast.removeAll()时能正常输出 “hello”
Toast.loading('xx',0,()=>console.log('hello'))
Toast.removeAll()
```
在本次的mr中并没有实现哦

**Comment by HuXin957** [comment]
> 针对 issue #1195 提出的
> 
> ```js
> // 在调用Toast.removeAll()时能正常输出 “hello”
> Toast.loading('xx',0,()=>console.log('hello'))
> Toast.removeAll()
> ```
> 
> 在本次的mr中并没有实现哦

这只是个设想。如果将回调放到打开loading的方法中，那只能固定时间后执行，在异步中是不符合需求的。所以只能将回调放到关闭loding的方法中。所以最终是我给removeAll、remove加了一个回调

**Comment by 1uokun** [comment]
那和
```
Toast.removeAll();
callback();
```
没什么区别呢

**Comment by erichua23** [comment]
> 针对 issue #1195 提出的
> 
> ```js
> // 在调用Toast.removeAll()时能正常输出 “hello”
> Toast.loading('xx',0,()=>console.log('hello'))
> Toast.removeAll()
> ```
> 
> 在本次的mr中并没有实现哦

如果只是实现这个功能，`componentWillUnmount`里面处理一下就行了。有动画的`onClose`依赖于动画结束的回调，`duration`为0的就直接单独根据 `WillUnmount` 来判断。
image

**Pull request closed without merging**
