### PR TITLE
Fix for Forked Repo error "Unable to resolve @ant-design/react-native/lib"

### PR DESCRIPTION
**Pull request by kvnlee777**
I'm trying to customize theme in Ant Design Mobile React-Native. I'm using Expo-cli.

I tried to fork https://github.com/ant-design/ant-design-mobile-rn

and customized the theme variables in https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/style/themes/default.tsx,

but when i install the forked repo and use import {Button} from '@ant-design/react-native/lib/button', it result to error "Unable to resolve @ant-design/react-native/lib".

Then I rename the folder "components" to "lib" and remove the /lib in .gitignore file and reinstall the forked repo. It now works, but i'm not sure what i did is right. Please help me check if it is the correct way to use a forked repo.

### CODE REVIEW

**Comment by bang88** [comment]
@kvnlee777 We use some tools to build it into lib folder and the components folder are the source files.

If you want fork it you can install deps and build it by yourself. If you just need modify the theme then you don't need fork a repo. just overwrite it via the `Provider` Component

Thank you.

**Comment by kvnlee777** [comment]
@bang88 Hi, can you send the instruction on how to build the forked repo?

**Comment by bang88** [comment]
- installing dependencies
- run `npm run compile`

**Comment by kvnlee777** [comment]
@bang88 Sorry i'm beginner. Do you mean after forking the repo and cloning the repo to local, i need to run `yarn install` then `run yarn run build`?

**Comment by bang88** [comment]
Yep

**Comment by kvnlee777** [comment]
@bang88 The yarn run build command is not found, so i tried yarn run compile, but it is not building the files. Do i have to include a script in package.json?

**Pull request closed without merging**
