### PR TITLE
pr #568

### PR DESCRIPTION
**Pull request by xinbowang**
1. package.json:

- yarn add @react-native-community/viewpager
- react-native link @react-native-community/viewpager

```
  dependencies:{
    @react-native-community/viewpager: "@react-native-community/viewpager": "^1.1.7",
  }
```
2. components/tabs.tsx
修改
```
import { Animated, Dimensions, LayoutChangeEvent, NativeScrollEvent, NativeSyntheticEvent, Platform, ScrollView，ViewPagerAndroid  } from 'react-native';
```
修改为
```
import { Animated, Dimensions, LayoutChangeEvent, NativeScrollEvent, NativeSyntheticEvent, Platform, ScrollView } from 'react-native';
import ViewPagerAndroid from '@react-native-community/viewpager';
```

### CODE REVIEW

**Comment by bang88** [comment]
这个改动不大但是影响比较大，等react-native 正式弃用view pager 的时候再合并这个吧。
要link 在expo之前的版本就用不了。

**Comment by xinbowang** [comment]
可以的。现在也不影响应用，只是老警告，比较烦人。




------------------ 原始邮件 ------------------
发件人: "启邦"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 上午10:11
收件人: "ant-design/ant-design-mobile-rn"<ant-design-mobile-rn@noreply.github.com>;
抄送: "龙博"<664176494@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-mobile-rn] pr #568 (#615)




这个改动不大但是影响比较大，等react-native 正式弃用view pager 的时候再合并这个吧。
 要link 在expo之前的版本就用不了。

**Comment by bang88** [comment]
> 可以的。现在也不影响应用，只是老警告，比较烦人。

react-native 没有不⚠️的。  习惯了

**Comment by xinbowang** [comment]
> > 可以的。现在也不影响应用，只是老警告，比较烦人。
> 
> react-native没有不⚠️的。习惯了

麻烦问下，我看react-mobile也可以应用到react-native为什么又做一个react-native-rn呢?

**Comment by xinbowang** [comment]
请教个问题：我看ant-mobile也是可以用到react-native中的，为什么还要单独做一个ant-mobile-rn呢？




------------------ 原始邮件 ------------------
发件人: "启邦"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 上午10:29
收件人: "ant-design/ant-design-mobile-rn"<ant-design-mobile-rn@noreply.github.com>;
抄送: "龙博"<664176494@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-mobile-rn] pr #568 (#615)



 
可以的。现在也不影响应用，只是老警告，比较烦人。
  
react-native 没有不⚠️的。  习惯了

**Comment by bang88** [comment]
mobile 是for web的。 rn才是react native的

**Comment by fallenner** [comment]
0.61.1 版本已经移除了。 还有0.61.1 Android版本Toast组件变白

**Comment by bang88** [comment]
> 0.61.1 版本已经移除了。 还有0.61.1 Android版本Toast组件变白

Toast 组件变白可以来个issue吗？

**Comment by fallenner** [comment]
> > 0.61.1 版本已经移除了。 还有0.61.1 Android版本Toast组件变白
> 
> Toast 组件变白可以来个issue吗？

已经提了  [650](https://github.com/ant-design/ant-design-mobile-rn/issues/650)

**Comment by campcc** [comment]
官方 Demo Tabs 组件引入直接报红屏了，原因就是引入@react-native-community/viewpager，pr都不用跑一下的吗？

**Comment by huan0118** [comment]
"dependencies": {
    "@ant-design/icons-react-native": "^2.2.1",
    "@ant-design/react-native": "^3.3.0",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/cameraroll": "^4.0.0",
    "@react-native-community/viewpager": "^4.1.0",
    "aliyun-oss-react-native": "^1.0.0-alpha.7",
    "axios": "^0.19.0",
    "buffer": "^5.4.3",
    "jcore-react-native": "1.3.2",
    "jpush-react-native": "2.2.13",
    "lodash": "^4.17.15",
    "md5": "^2.2.1",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-android-location-services-dialog-box": "^2.8.2",
    "react-native-calendars": "^1.217.0",
    "react-native-circular-progress": "^1.3.6",
    "react-native-code-push": "^6.2.1",
    "react-native-communications": "^2.2.1",
    "react-native-contacts": "^5.2.3",
    "react-native-device-info": "^5.4.0",
    "react-native-drag-sort": "^1.3.6",
    "react-native-dropdownalert": "^4.2.0",
    "react-native-fs": "^2.16.2",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-idle-timer": "^2.1.6",
    "react-native-image-marker": "^0.6.1",
    "react-native-image-picker": "^1.1.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-permissions": "^2.1.5",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-render-html": "^4.2.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-sound": "^0.11.0",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "^12.0.3",
    "react-native-svg-uri": "^1.2.3",
    "react-native-webview": "^8.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/plugin-proposal-decorators": "^7.7.4",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^24.0.23",
    "@types/react": "^16.9.16",
    "@types/react-native": "^0.60.25",
    "@types/react-redux": "^7.1.5",
    "@types/react-test-renderer": "^16.9.1",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "16.9.0",
    "typescript": "^3.7.3"
  },



安卓模拟器直接崩溃 运行不起来

**Comment by zxkNoir** [comment]
> 官方 Demo Tabs 组件引入直接报红屏了，原因就是引入@react-native-community/viewpager，pr都不用跑一下的吗？

请问一下大佬，这种情况可以直接替换成react-native-pager-view吗，初学antd的demo就一直报这个viewpager的错

**Comment by 1uokun** [comment]
> > 官方 Demo Tabs 组件引入直接报红屏了，原因就是引入@react-native-community/viewpager，pr都不用跑一下的吗？
> 
> 请问一下大佬，这种情况可以直接替换成react-native-pager-view吗，初学antd的demo就一直报这个viewpager的错

先用@react-native-picker/picker(https://github.com/ant-design/ant-design-mobile-rn/issues/1120) 依赖，等社区稳定了我们会出一个正式包

**Pull request merged**
