### PR TITLE
feat: Carousel supports vertical

### PR DESCRIPTION
**Pull request by jlsnake**
For this issue #26 and fix the selectedIndex display error in issue #7 

* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

*isNewFeature* **:**

  * [x] Update API docs for the component.
  * [x] Update/Add demo to demonstrate new feature.
  * [x] Update TypeScript definition for the component.
  * [x] Add unit tests for the feature.

### CODE REVIEW

**Comment by warmhug** [comment]
> It seems that there is a `drag problem` on Android 4.1

But it works well on Android 7 and iOS. Thank you for your great work!

**Comment by warmhug** [comment]
Close #26

**Comment by youngjuning** [comment]
但是还是有问题啊，竖屏的时候，初始化显示会有问题

**Comment by jlsnake** [comment]
什么问题？

**Comment by xiaohuoni** [comment]
类似这种使用方式，可以规避掉，初始化显示的问题，还有不会 autoplay 的问题。
```
{data&&<Carousel/>}
```

**Pull request merged**
